### ISSUE TITLE
Absolute path to submodule in .gitmodules file.

### ISSUE THREAD

**Issue by Paebbels** [OSVVM/OsvvmLibraries#17]
`.gitmodules` still contains an absolute submodule path.  
Didn't we fix it some time ago?

https://github.com/OSVVM/OsvvmLibraries/blob/0f8e90eb817fd87543f684942af2591644e627a6/.gitmodules#L21

**Comment by JimLewis** [comment]
I thought I had done it already on Dev.   Apparently not.   I just updated it and pushed it to Dev.   Let me know if that messed anything up as I only modified the one file.

**Comment by JimLewis** [comment]
fixed in Dev.
