### ISSUE TITLE
Cannot use OsvvmLibraries.pro to compile external library for VUnit with Riviera-PRO

### ISSUE THREAD

**Issue by as266** [OSVVM/OsvvmLibraries#8]
Hi,
I am unable to use OSVVM as compiled by the OsvvmLibraries.pro script as an external library in VUnit. This seems to be because the physical_name parameter of the vmap/amap command in Riviera-PRO requires either:
1. The path to the directory of the .lib file, where the file has the same name as the containing directory with the .lib extension
2. The path to the .lib file itself, with or without the .lib extension, the lib file and the directory name do not have to match

VUnit supports only 1), whereas OSVVM when compiled using the included scripts requires 2).

I have also raised this at https://github.com/VUnit/vunit/issues/754.

**Comment by JimLewis** [comment]
I am looking at an alternative solution that keeps the .lib extension

**Comment by JimLewis** [comment]
Alternative solution does not work, so removing the ".lib extension was necessary from the vendor library paths to make Riviera-PRO happy.

**Comment by JimLewis** [comment]
Closing this as .lib is no longer part of OSVVM library directory names.

**Comment by JimLewis** [comment]
@as266  2021.12 updated OSVVM library handling.   In addition, I just pushed some changes to OSVVM's LinkLibrary, to better support linking to externally generated libraries - previously it had a limitation in that it expected a particular naming pattern for the libraries and only then would link the library.
