### ISSUE TITLE
Very Minor Typo: ScoreboardPkg quickref

### ISSUE THREAD

**Issue by a-panella** [OSVVM/OsvvmLibraries#9]
In the quickref, section 4.2 has the same explanation as section 4.3. Both appear to be the explanation for section 4.3, meaning section 4.2 might need to be updated.
![scoreboardpkg](https://user-images.githubusercontent.com/22805069/139778636-3a198d28-58bf-40eb-b685-02e90d8bc5ad.png)

**Comment by JimLewis** [comment]
@a-panella  Thanks.   I pushed an updated ScoreboardPkg quickreference.
